home:
    pattern:  /
    defaults: { _controller: ObtaoBlogBundle:Common:index }

obtao-article-search:
    pattern:  /article/list
    defaults: { _controller: ObtaoBlogBundle:Article:list }

obtao-article-export:
    pattern:  /article/export
    defaults: { _controller: ObtaoBlogBundle:Article:export }